name = "UFF"
uuid = "0d0b83d6-456a-42e3-bf29-fb85441d02cf"
authors = ["Simon Andreas Bjørn <s.a.bjorn@ifi.uio.no> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
